# project prot
server:
  port: 9999
  mvc:
    throw-exception-if-no-handler-found: true # 告诉 SpringBoot 当出现 404 错误时, 直接抛出异常
  resources:
    add-mappings: false # 告诉 SpringBoot 不要为我们工程中的资源文件建立映射

# database config
mysql:
  database: wall
  port: 3307
  ip: 127.0.0.1
  username: root
  password: 123456

# spring config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: ${mysql.username}
    password: ${mysql.password}

# file upload size
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

# MyBatis conf
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.ityao.wall.entity

project-info:
  version: version@
